# fly.toml app configuration file generated for fullstackopen-part-13 on 2024-12-08T04:18:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstackopen-part-13'
primary_region = 'arn'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
